
package clientews.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "INoteDao", targetNamespace = "http://interfaces/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface INoteDao {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.Note>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllByUser", targetNamespace = "http://interfaces/", className = "clientews.servicio.GetAllByUser")
    @ResponseWrapper(localName = "getAllByUserResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.GetAllByUserResponse")
    @Action(input = "http://interfaces/INoteDao/getAllByUserRequest", output = "http://interfaces/INoteDao/getAllByUserResponse")
    public List<Note> getAllByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<clientews.servicio.Note>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllN", targetNamespace = "http://interfaces/", className = "clientews.servicio.GetAllN")
    @ResponseWrapper(localName = "getAllNResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.GetAllNResponse")
    @Action(input = "http://interfaces/INoteDao/getAllNRequest", output = "http://interfaces/INoteDao/getAllNResponse")
    public List<Note> getAllN();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addN", targetNamespace = "http://interfaces/", className = "clientews.servicio.AddN")
    @ResponseWrapper(localName = "addNResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.AddNResponse")
    @Action(input = "http://interfaces/INoteDao/addNRequest", output = "http://interfaces/INoteDao/addNResponse")
    public boolean addN(
        @WebParam(name = "arg0", targetNamespace = "")
        Note arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteN", targetNamespace = "http://interfaces/", className = "clientews.servicio.DeleteN")
    @ResponseWrapper(localName = "deleteNResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.DeleteNResponse")
    @Action(input = "http://interfaces/INoteDao/deleteNRequest", output = "http://interfaces/INoteDao/deleteNResponse")
    public boolean deleteN(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateN", targetNamespace = "http://interfaces/", className = "clientews.servicio.UpdateN")
    @ResponseWrapper(localName = "updateNResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.UpdateNResponse")
    @Action(input = "http://interfaces/INoteDao/updateNRequest", output = "http://interfaces/INoteDao/updateNResponse")
    public boolean updateN(
        @WebParam(name = "arg0", targetNamespace = "")
        Note arg0);

}
