
package clientews.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUserDao", targetNamespace = "http://interfaces/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUserDao {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://interfaces/", className = "clientews.servicio.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.AddResponse")
    @Action(input = "http://interfaces/IUserDao/addRequest", output = "http://interfaces/IUserDao/addResponse")
    public boolean add(
        @WebParam(name = "arg0", targetNamespace = "")
        Note arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://interfaces/", className = "clientews.servicio.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.UpdateResponse")
    @Action(input = "http://interfaces/IUserDao/updateRequest", output = "http://interfaces/IUserDao/updateResponse")
    public boolean update(
        @WebParam(name = "arg0", targetNamespace = "")
        Note arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://interfaces/", className = "clientews.servicio.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.DeleteResponse")
    @Action(input = "http://interfaces/IUserDao/deleteRequest", output = "http://interfaces/IUserDao/deleteResponse")
    public boolean delete(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<clientews.servicio.Note>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://interfaces/", className = "clientews.servicio.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.GetAllResponse")
    @Action(input = "http://interfaces/IUserDao/getAllRequest", output = "http://interfaces/IUserDao/getAllResponse")
    public List<Note> getAll();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyCredentials", targetNamespace = "http://interfaces/", className = "clientews.servicio.VerifyCredentials")
    @ResponseWrapper(localName = "verifyCredentialsResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.VerifyCredentialsResponse")
    @Action(input = "http://interfaces/IUserDao/verifyCredentialsRequest", output = "http://interfaces/IUserDao/verifyCredentialsResponse")
    public boolean verifyCredentials(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
